### ISSUE TITLE
web not displaying

### ISSUE THREAD

**Issue by 007scorpio** [ciscocsirt/GOSINT#15]
Web not displaying after visiting localhost....

**Comment by iamtmehdi** [comment]
To start to debug the issue:

- Are you receiving any HTTP status error when you try to load the web interface (404, 500, etc)?
- Can you navigate to http://localhost/api/pre/ and see if the API backend is functioning as expected?

Thanks.

**Comment by 007scorpio** [comment]
Error message is 404

Thanks

**Comment by jeff-bollinger** [comment]
Works for me - try the docker image

**Comment by azfayel** [comment]
OK why the nginx do not display the dashboard when entering localhost in web browse ?
How to debug that.

**Comment by blueteam1** [comment]
Hello, 

Unfortunately we do not have the resources at this time to provide personalized support on getting the framework running which is why we tried our best to document it all out.  If you feel there is a bug in the software or the documentation, please provide a detailed explanation and ideally a submit a fix if you find one.

Thanks
