### ISSUE TITLE
I set up Threat Intel APIs,but No indicators found

### ISSUE THREAD

**Issue by njzy** [ciscocsirt/GOSINT#16]
I set up Threat Intel APIs,but No indicators found
![gosint](https://user-images.githubusercontent.com/9823010/35278549-628f5378-0085-11e8-8da1-770c2c6fa58a.png)

**Comment by blueteam1** [comment]
Hello, 

First, I suggest you try and edit out this picture as you're presumably exposing your Alienvault and VirusTotal API keys to the public internet.  You should probably generate new API keys since it is now unknown who can be viewing them.

In regards to the issue, the Alienvault crawler only runs once every 24 hours.  If you haven't already, please give it some time to run and populate.  Having a Virustotal key configured will not yield any indicators by its self or with an Alienvault key.

I'm closing this bug, if you have further issues, feel free to open a new one with more information but without any private information like API keys please.

Thanks
