### ISSUE TITLE
Web interface AJAX issues

### ISSUE THREAD

**Issue by Psylence7** [ciscocsirt/GOSINT#9]
Hello all,

I'm not sure if I'm missing something obvious but I've been trying to get this working for a number of hours now and I don't know what step I appear to be missing or doing wrong that's causing AJAX errors. I've followed the manual installation guide as outlined, provided any prerequisites and yet still when I try to load the settings page:

![image](https://user-images.githubusercontent.com/5718240/31020349-a7abaf08-a52a-11e7-979f-f4ca4f1c056e.png)

If I complete any of the fields and try to Update, instead of 2 AJAX errors I get 1 "submitted to Endpoint" response and 1 AJAX error popup. But refreshing the page simply wipes all the fields and I'm back to where I started. I'm deploying on Ubuntu Server 16.04.

**Comment by blueteam1** [comment]
Hey Psylence7,

Best way to troubleshoot an issue such as this is to check your web server logs.  You should see error logs when the web server attempts to proxy the connection to the backend.  This will tell you if you're having issues like a misconfigured IP address or port in the web server proxy configuration.

Otherwise, there's a handful of other issues that it could possibly be such as the backend is not running or there's something inhibiting the network connection.

**Comment by rt5v3y02fk** [comment]
You probably have this fixed now, but I had the same issue and I just had to start gosint again.

**Comment by Ayd-Nr** [comment]
Hello all,

I have same problem with ajax requests. 
The error logs below:

2018/01/07 16:35:00 [error] 1279#1279: *59 connect() failed (111: Connection refused) while connecting to upstream, client: X.X.X.X, server: Y.Y.Y.Y, request: "GET /api/settings/feeds/?_=1515360978572 HTTP/1.1", upstream: "http://[::1]:8000/api/settings/feeds/?_=1515360978572", host: "Y.Y.Y.Y", referrer: "http://Y.Y.Y.Y/settings.php"

2018/01/07 16:35:00 [error] 1279#1279: *59 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: X.X.X.X, server: Y.Y.Y.Y, request: "GET /api/settings/feeds/?_=1515360978572 HTTP/1.1", upstream: "http://[::1]:8000/api/settings/feeds/?_=1515360978572", host: "Y.Y.Y.Y", referrer: "http://Y.Y.Y.Y/settings.php"

best regards

**Comment by blueteam1** [comment]
Hello,

Unfortunately we do not have the resources at this time to provide personalized support on getting the framework running which is why we tried our best to document it all out. If you feel there is a bug in the software or the documentation, please provide a detailed explanation and ideally submit a fix if you find one.

Thanks
